name: Deno CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Dependencies
        run: deno cache --unstable deps.ts

      - name: Run Linter
        run: deno lint path/to/lint/directory # Customize path

      - name: Run Tests
        run: deno test -A --unstable tests/**/*.test.ts # Customize test path
